#!/usr/bin/env python3
"""Discover RSS feeds for news sources listed in news_sources.csv."""

import asyncio
import aiohttp
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
import csv
import os
import sys
import re

INPUT_CSV = os.path.join(os.path.dirname(__file__), "news_sources.csv")
OUTPUT_CSV = os.path.join(os.path.dirname(__file__), "news_sources_with_rss.csv")

# ---------------------------------------------------------------------------
# Known RSS feeds — manually curated
# Key = exact "Source Name" value in the CSV
# ---------------------------------------------------------------------------
KNOWN_RSS: dict[str, str] = {
    # ── United States ────────────────────────────────────────────────────────
    "The New York Times": "https://rss.nytimes.com/services/xml/rss/nf/HomePage.xml",
    "The Washington Post": "https://feeds.washingtonpost.com/rss/homepage",
    "The Wall Street Journal": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
    "USA Today": "http://rssfeeds.usatoday.com/usatoday-NewsTopStories",
    "Los Angeles Times": "https://www.latimes.com/world/rss2.0.xml",
    "Chicago Tribune": "https://www.chicagotribune.com/arcio/rss/",
    "The Boston Globe": "https://www.bostonglobe.com/rss/headlines",
    "San Francisco Chronicle": "https://www.sfchronicle.com/news/rss",
    "The Associated Press (AP)": "https://feeds.apnews.com/rss/apf-topnews",
    "Reuters (US Bureau)": "https://feeds.reuters.com/reuters/topNews",
    "NPR": "https://feeds.npr.org/1001/rss.xml",
    "PBS NewsHour": "https://www.pbs.org/newshour/feeds/rss/headlines",
    "CNN": "http://rss.cnn.com/rss/edition.rss",
    "MSNBC": "http://www.msnbc.com/feeds/latest",
    "Fox News": "https://moxie.foxnews.com/google-publisher/latest.xml",
    "ABC News": "https://abcnews.go.com/abcnews/topstories",
    "CBS News": "https://www.cbsnews.com/latest/rss/main",
    "NBC News": "https://feeds.nbcnews.com/nbcnews/public/news",
    "Bloomberg": "https://feeds.bloomberg.com/markets/news.rss",
    "Politico": "https://rss.politico.com/politics-news.xml",
    "The Hill": "https://thehill.com/feed/",
    "Axios": "https://api.axios.com/feed/",
    "The Atlantic": "https://www.theatlantic.com/feed/all/",
    "The New Yorker": "https://www.newyorker.com/feed/news",
    "Vox": "https://www.vox.com/rss/index.xml",
    "HuffPost": "https://www.huffpost.com/section/front-page/feed",
    "Mother Jones": "https://www.motherjones.com/feed/",
    "The Intercept": "https://theintercept.com/feed/?rss",
    "Democracy Now!": "https://www.democracynow.org/democracynow.rss",
    "Jacobin": "https://jacobin.com/feed/",
    "The Nation": "https://www.thenation.com/feed/?post_type=article",
    "National Review": "https://www.nationalreview.com/feed/",
    "The Daily Wire": "https://www.dailywire.com/feeds/rss.xml",
    "The Federalist": "https://thefederalist.com/feed/",
    "Breitbart": "http://feeds.feedburner.com/breitbart",
    "The Epoch Times": "https://www.theepochtimes.com/feed",
    "Newsmax": "https://www.newsmax.com/rss/Newsmax-Top-Newsstories/1/",
    "The American Conservative": "https://www.theamericanconservative.com/feed/",
    "Reason": "https://reason.com/feed/",
    "ProPublica": "https://feeds.propublica.org/propublica/main",
    "The Marshall Project": "https://www.themarshallproject.org/feeds/published",
    "Foreign Affairs": "https://www.foreignaffairs.com/rss.xml",
    "Foreign Policy": "https://foreignpolicy.com/feed/",
    "The Dispatch": "https://thedispatch.com/feed/",
    "Semafor": "https://www.semafor.com/rss",
    "The Free Press": "https://www.thefp.com/feed",
    # ── Canada ────────────────────────────────────────────────────────────────
    "CBC News": "https://www.cbc.ca/cmlink/rss-topstories",
    "CTV News": "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009",
    "Global News": "https://globalnews.ca/feed/",
    "The Globe and Mail": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/",
    "National Post": "https://nationalpost.com/feed",
    "Toronto Star": "https://www.thestar.com/content/thestar/feed.RSSManagerServlet.articles.topstories.rss",
    "The Walrus": "https://thewalrus.ca/feed/",
    "Maclean's": "https://macleans.ca/feed/",
    "Rebel News": "https://www.rebelnews.com/feed",
    "The Narwhal": "https://thenarwhal.ca/feed/",
    "The Tyee": "https://thetyee.ca/feed/",
    # ── Mexico ────────────────────────────────────────────────────────────────
    "El Universal": "https://www.eluniversal.com.mx/rss.xml",
    "La Jornada": "https://www.jornada.com.mx/rss/edicion.xml",
    "Milenio": "https://www.milenio.com/rss",
    "Proceso": "https://www.proceso.com.mx/rss/",
    "Animal Político": "https://www.animalpolitico.com/feed",
    "Aristegui Noticias": "https://aristeguinoticias.com/feed/",
    "SinEmbargo": "https://www.sinembargo.mx/feed",
    # ── Brazil ────────────────────────────────────────────────────────────────
    "Folha de S.Paulo": "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml",
    "O Globo": "https://oglobo.globo.com/rss.xml",
    "O Estado de S. Paulo (Estadão)": "https://www.estadao.com.br/rss/ultimas-noticias",
    "Valor Econômico": "https://valor.globo.com/rss.xml",
    "The Intercept Brasil": "https://theintercept.com/brasil/feed/?rss",
    "UOL": "https://rss.home.uol.com.br/index.xml",
    "Nexo Jornal": "https://www.nexojornal.com.br/feeds/rss",
    # ── Argentina ────────────────────────────────────────────────────────────
    "Clarín": "https://www.clarin.com/rss/ultimo-momento/",
    "La Nación": "https://www.lanacion.com.ar/arcio/rss/",
    "Página/12": "https://www.pagina12.com.ar/rss",
    "Infobae": "https://www.infobae.com/feeds/rss/",
    "Perfil": "https://www.perfil.com/feed",
    # ── Colombia ────────────────────────────────────────────────────────────
    "El Tiempo": "https://www.eltiempo.com/rss/ultimas_noticias.xml",
    "El Espectador": "https://www.elespectador.com/arc/outboundfeeds/rss/",
    "Semana": "https://www.semana.com/rss-feed/",
    # ── Chile ────────────────────────────────────────────────────────────────
    "El Mercurio": "https://www.emol.com/rss/_utilidades/rssExport.aspx?idcategoria=0",
    "La Tercera": "https://www.latercera.com/feed/",
    "BioBioChile": "https://www.biobiochile.cl/feed",
    # ── Peru ────────────────────────────────────────────────────────────────
    "El Comercio": "https://elcomercio.pe/arcio/rss/",
    "La República": "https://larepublica.pe/rss/",
    "RPP Noticias": "https://rpp.pe/rss/feed",
    # ── UK ────────────────────────────────────────────────────────────────────
    "BBC News": "http://feeds.bbci.co.uk/news/rss.xml",
    "The Guardian": "https://www.theguardian.com/world/rss",
    "The Times": "https://www.thetimes.co.uk/rss/feed",
    "The Daily Telegraph": "https://www.telegraph.co.uk/rss.xml",
    "Financial Times": "https://www.ft.com/world?format=rss",
    "The Independent": "https://www.independent.co.uk/news/rss",
    "The Economist": "https://www.economist.com/rss/the_world_this_week_rss.xml",
    "Daily Mail": "https://www.dailymail.co.uk/articles.rss",
    "The Sun": "https://www.thesun.co.uk/feed/",
    "Daily Mirror": "https://www.mirror.co.uk/news/?service=rss",
    "The Observer": "https://www.theguardian.com/theobserver/rss",
    "Sky News": "https://feeds.skynews.com/feeds/rss/home.xml",
    "Channel 4 News": "https://www.channel4.com/news/feed/topstories/rss.xml",
    "The Spectator": "https://www.spectator.co.uk/feed/",
    "New Statesman": "https://www.newstatesman.com/feed",
    "GB News": "https://www.gbnews.com/feeds/news.rss",
    "UnHerd": "https://unherd.com/feed/",
    "Bureau of Investigative Journalism": "https://www.thebureauinvestigates.com/feed",
    # ── France ────────────────────────────────────────────────────────────────
    "Le Monde": "https://www.lemonde.fr/rss/une.xml",
    "Le Figaro": "https://www.lefigaro.fr/rss/figaro_actualites.xml",
    "Libération": "https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml",
    "France 24": "https://www.france24.com/en/rss",
    "Mediapart": "https://www.mediapart.fr/articles/feed",
    "L'Humanité": "https://www.humanite.fr/feed",
    "Le Point": "https://www.lepoint.fr/rss.xml",
    "L'Obs (Nouvel Obs)": "https://www.nouvelobs.com/rss.xml",
    "AFP (Agence France-Presse)": "https://www.afp.com/en/rss-feeds",
    "RFI": "https://www.rfi.fr/en/rss-feeds",
    "BFM TV": "https://www.bfmtv.com/rss/info/flux-rss/",
    # ── Germany ────────────────────────────────────────────────────────────────
    "Der Spiegel": "https://www.spiegel.de/schlagzeilen/index.rss",
    "Die Zeit": "https://newsfeed.zeit.de/index",
    "Süddeutsche Zeitung": "https://rss.sueddeutsche.de/rss/topthemen",
    "Frankfurter Allgemeine Zeitung (FAZ)": "https://www.faz.net/rss/aktuell/",
    "Die Welt": "https://www.welt.de/feeds/latest.rss",
    "Bild": "https://www.bild.de/rssfeeds/rss3-20745882,short=1/rss3-20745882,short=1.bild.xml",
    "Handelsblatt": "https://www.handelsblatt.com/contentexport/feed/schlagzeilen",
    "Deutsche Welle (DW)": "https://rss.dw.com/rdf/rss-en-all",
    "taz (die tageszeitung)": "https://taz.de/!p4608;rss/",
    "Correctiv": "https://correctiv.org/feed/",
    # ── Italy ────────────────────────────────────────────────────────────────
    "Corriere della Sera": "https://xml2.corriereobjects.it/rss/homepage.xml",
    "La Repubblica": "https://www.repubblica.it/rss/homepage/rss2.0.xml",
    "La Stampa": "https://www.lastampa.it/rss",
    "Il Sole 24 Ore": "https://www.ilsole24ore.com/rss/italia--e-mondo.xml",
    "Il Fatto Quotidiano": "https://www.ilfattoquotidiano.it/feed/",
    "RAI News": "https://www.rainews.it/rss",
    "ANSA": "https://www.ansa.it/sito/ansait_rss.xml",
    "Domani": "https://www.editorialedomani.it/feed",
    # ── Spain ────────────────────────────────────────────────────────────────
    "El País": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "El Mundo": "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
    "ABC": "https://www.abc.es/rss/feeds/abc_EspanaEspana.xml",
    "La Vanguardia": "https://www.lavanguardia.com/mvc/feed/rss/home",
    "El Confidencial": "https://rss.elconfidencial.com/espana/",
    "elDiario.es": "https://www.eldiario.es/rss/",
    "RTVE": "https://www.rtve.es/api/videos/noticias/feed.rss",
    "EFE": "https://efenoticias.com/feed/",
    # ── Netherlands ─────────────────────────────────────────────────────────
    "De Volkskrant": "https://www.volkskrant.nl/rss.xml",
    "NRC Handelsblad": "https://www.nrc.nl/rss/",
    "De Telegraaf": "https://www.telegraaf.nl/rss",
    "Trouw": "https://www.trouw.nl/rss.xml",
    "NOS": "https://feeds.nos.nl/nosnieuwsalgemeen",
    # ── Belgium ─────────────────────────────────────────────────────────────
    "De Standaard": "https://www.standaard.be/rss/section/3dc3a6c4-4634-4b64-9a00-3bab2c4b73e0",
    "De Morgen": "https://www.demorgen.be/rss.xml",
    "Le Soir": "https://www.lesoir.be/arc/outboundfeeds/rss/",
    "VRT NWS": "https://www.vrt.be/vrtnws/nl.rss.articles.xml",
    "RTBF": "https://www.rtbf.be/api/sso/v1/news/articles?rss",
    # ── Switzerland ─────────────────────────────────────────────────────────
    "Neue Zürcher Zeitung (NZZ)": "https://www.nzz.ch/recent.rss",
    "Tages-Anzeiger": "https://www.tagesanzeiger.ch/rss.html",
    "Le Temps": "https://www.letemps.ch/rss",
    "Blick": "https://www.blick.ch/news/rss.xml",
    "Republik": "https://www.republik.ch/feed.xml",
    # ── Austria ─────────────────────────────────────────────────────────────
    "Der Standard": "https://www.derstandard.at/rss",
    "Die Presse": "https://www.diepresse.com/rss/home",
    "ORF": "https://rss.orf.at/news.xml",
    "Profil": "https://www.profil.at/rss/",
    # ── Portugal ─────────────────────────────────────────────────────────────
    "Público": "https://www.publico.pt/api/rss",
    "Diário de Notícias": "https://www.dn.pt/rss/",
    "Expresso": "https://expresso.pt/rss",
    "Observador": "https://observador.pt/feed/",
    "RTP": "https://www.rtp.pt/noticias/rss.php",
    # ── Ireland ─────────────────────────────────────────────────────────────
    "The Irish Times": "https://www.irishtimes.com/cmlink/news-rss-1.1319291",
    "Irish Independent": "https://www.independent.ie/rss/",
    "RTÉ": "https://www.rte.ie/rss/news.xml",
    "The Journal.ie": "https://www.thejournal.ie/feed/",
    # ── Nordics ─────────────────────────────────────────────────────────────
    "Dagens Nyheter": "https://www.dn.se/rss/",
    "Svenska Dagbladet (SvD)": "https://www.svd.se/?service=rss",
    "Aftonbladet": "https://rss.aftonbladet.se/rss2/small/pages/sections/senastenytt/",
    "SVT Nyheter": "https://www.svt.se/nyheter/rss.xml",
    "Aftenposten": "https://www.aftenposten.no/rss",
    "VG (Verdens Gang)": "https://www.vg.no/rss/feed/forsiden/",
    "NRK": "https://www.nrk.no/toppsaker.rss",
    "Politiken": "https://politiken.dk/rss/senestenyheder.rss",
    "Berlingske": "https://www.berlingske.dk/rss/",
    "Jyllands-Posten": "https://jyllands-posten.dk/feed/",
    "DR (Danmarks Radio)": "https://www.dr.dk/nyheder/service/feeds/allenyheder",
    "Helsingin Sanomat": "https://www.hs.fi/rss/tuoreimmat.xml",
    "Yle": "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_UUTISET",
    # ── Eastern Europe ───────────────────────────────────────────────────────
    "Gazeta Wyborcza": "https://rss.gazeta.pl/pub/rss/wyborcza_kraj.xml",
    "Hospodářské noviny": "https://archiv.hn.cz/rss/",
    "Telex": "https://telex.hu/rss",
    # ── Ukraine / Russia / etc ───────────────────────────────────────────────
    "Ukrainska Pravda": "https://www.pravda.com.ua/eng/rss/",
    "Kyiv Independent": "https://kyivindependent.com/feed/",
    "Meduza": "https://meduza.io/rss/all",
    "The Moscow Times": "https://www.themoscowtimes.com/rss/news",
    "TASS": "https://tass.com/rss/v2.xml",
    "RIA Novosti": "https://ria.ru/export/rss2/archive/index.xml",
    # ── Middle East ──────────────────────────────────────────────────────────
    "Al Jazeera": "https://www.aljazeera.com/xml/rss/all.xml",
    "Al Jazeera English": "https://www.aljazeera.com/xml/rss/all.xml",
    "Haaretz": "https://www.haaretz.com/srv/haaretz-en-rss-new.xml",
    "The Times of Israel": "https://www.timesofisrael.com/feed/",
    "The Jerusalem Post": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
    "Arab News": "https://www.arabnews.com/rss.xml",
    "Al Arabiya": "https://www.alarabiya.net/tools/rss",
    "Al-Monitor (Egypt coverage)": "https://www.al-monitor.com/rss",
    "Iran International": "https://www.iranintl.com/en/rss",
    # ── Asia ────────────────────────────────────────────────────────────────
    "South China Morning Post": "https://www.scmp.com/rss/91/feed",
    "The Straits Times": "https://www.straitstimes.com/news/world/rss.xml",
    "Channel NewsAsia (CNA)": "https://www.channelnewsasia.com/rssfeeds/8395986",
    "The Japan Times": "https://www.japantimes.co.jp/feed/",
    "NHK": "https://www3.nhk.or.jp/rss/news/cat0.xml",
    "The Asahi Shimbun": "https://www.asahi.com/rss/asahi/newsheadlines.rdf",
    "The Hindu": "https://www.thehindu.com/feeder/default.rss",
    "The Times of India": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    "Hindustan Times": "https://www.hindustantimes.com/feeds/rss/latest-news/rssfeed.xml",
    "The Indian Express": "https://indianexpress.com/feed/",
    "NDTV": "https://feeds.feedburner.com/ndtvnews-top-stories",
    "The Wire": "https://thewire.in/rss/",
    "Scroll.in": "https://scroll.in/rss",
    "The Print": "https://theprint.in/feed/",
    "Dawn": "https://www.dawn.com/feeds/home",
    "Geo TV": "https://www.geo.tv/rss",
    "The Daily Star": "https://www.thedailystar.net/rss.xml",
    "The Kathmandu Post": "https://kathmandupost.com/rss",
    "Bangkok Post": "https://www.bangkokpost.com/rss/data/topstories.xml",
    "Philippine Daily Inquirer": "https://www.inquirer.net/rss",
    "Rappler": "https://www.rappler.com/feed/",
    "Jakarta Post": "https://www.thejakartapost.com/feed/",
    "Kompas": "https://rss.kompas.com/",
    "Vietnam News Agency": "https://en.vietnamplus.vn/rss/home.rss",
    "VnExpress": "https://vnexpress.net/rss/tin-muc-moi-nhat.rss",
    "Hong Kong Free Press": "https://hongkongfp.com/feed/",
    "The Korea Herald": "https://www.koreaherald.com/common/rss_xml.php?ct=102",
    "Yonhap News": "https://en.yna.co.kr/RSS/news.xml",
    "Malaysiakini": "https://www.malaysiakini.com/rss",
    "Civil.ge": "https://civil.ge/feed",
    "Xinhua": "https://www.xinhuanet.com/english/rss/worldrss.xml",
    "People's Daily": "http://en.people.cn/rss/politics_rss.xml",
    "Global Times": "https://www.globaltimes.cn/rss/outbrain.xml",
    "CGTN": "https://www.cgtn.com/subscribe/feeds/rss2.0.xml",
    "Caixin": "https://www.caixinglobal.com/rss/rss.xml",
    # ── Africa ───────────────────────────────────────────────────────────────
    "Daily Maverick": "https://www.dailymaverick.co.za/feed/",
    "Mail & Guardian": "https://mg.co.za/feed",
    "News24": "https://feeds.24.com/articles/news24/TopStories/rss",
    "The Punch": "https://punchng.com/feed/",
    "Premium Times": "https://www.premiumtimesng.com/feed",
    "Daily Nation": "https://nation.africa/rss/",
    "The Standard (Kenya)": "https://www.standardmedia.co.ke/rss/headlines.php",
    "Addis Standard": "https://addisstandard.com/feed/",
    # ── Oceania ──────────────────────────────────────────────────────────────
    "ABC News (Australia)": "https://www.abc.net.au/news/feed/51120/rss.xml",
    "SBS News": "https://www.sbs.com.au/news/topic/latest/feed",
    "The Sydney Morning Herald": "https://www.smh.com.au/rss/feed.xml",
    "The Age": "https://www.theage.com.au/rss/feed.xml",
    "The Australian": "https://www.theaustralian.com.au/feed",
    "The Guardian Australia": "https://www.theguardian.com/australia-news/rss",
    "NZ Herald": "https://www.nzherald.co.nz/arc/outboundfeeds/rss/",
    "Stuff": "https://www.stuff.co.nz/rss",
    "RNZ (Radio NZ)": "https://www.rnz.co.nz/rss/latest.rss",
    # ── Global ───────────────────────────────────────────────────────────────
    "Reuters": "https://feeds.reuters.com/reuters/topNews",
    "Associated Press (AP)": "https://feeds.apnews.com/rss/apf-topnews",
    "Agence France-Presse (AFP)": "https://www.afp.com/en/rss-feeds",
    "BBC World Service": "http://feeds.bbci.co.uk/news/world/rss.xml",
    "Voice of America (VOA)": "https://www.voanews.com/api/zm_qoinkqqpe",
    "Radio Free Europe / Radio Liberty (RFE/RL)": "https://www.rferl.org/api/epiqq",
    "Deutsche Welle (DW)": "https://rss.dw.com/rdf/rss-en-all",
    "France 24": "https://www.france24.com/en/rss",
    "NHK World-Japan": "https://www3.nhk.or.jp/nhkworld/en/news/feeds/",
    "OCCRP": "https://www.occrp.org/en/component/k2/feed/",
    "Bellingcat": "https://www.bellingcat.com/feed/",
    "openDemocracy": "https://www.opendemocracy.net/en/rss.xml",
    # ── Additional / previously missing ─────────────────────────────────────
    "Le Devoir": "https://www.ledevoir.com/rss.xml",
    "El Heraldo": "https://www.elheraldo.hn/rss",
    "La Prensa Gráfica": "https://www.laprensagrafica.com/rss.xml",
    "Listín Diario": "https://listindiario.com/feed",
    "Le Nouvelliste": "https://lenouvelliste.com/rss.xml",
    "Caracol TV/Radio": "https://www.caracoltv.com/rss",
    "RCN": "https://www.rcnradio.com/feed",
    "Tal Cual": "https://talcualdigital.com/feed",
    "El Universo": "https://www.eluniverso.com/rss",
    "GK (formerly GkillCity)": "https://gk.city/feed/",
    "ABC Color": "https://www.abc.com.py/rss",
    "Última Hora": "https://www.ultimahora.com/feed",
    "La Diaria": "https://ladiaria.com.uy/feed/",
    "El Observador": "https://www.elobservador.com.uy/rss.xml",
    "Dagbladet": "https://www.dagbladet.no/rss/",
    "Rzeczpospolita": "https://www.rp.pl/rss/",
    "TVN24": "https://tvn24.pl/najnowsze.xml",
    "wSieci / wPolityce": "https://wpolityce.pl/feed",
    "iDNES.cz": "https://www.idnes.cz/rss/",
    "Parlamentní listy": "https://www.parlamentnilisty.cz/rss/",
    "Index.hu": "https://index.hu/24ora/rss/",
    "Origo.hu": "https://www.origo.hu/contentpartner/rss/itthon/origo.xml",
    "România Liberă": "https://romanialibera.ro/feed",
    "Capital (BG)": "https://www.capital.bg/rss/",
    "Dnevnik (BG)": "https://www.dnevnik.bg/rss/",
    "Dnevnik (SI)": "https://www.dnevnik.si/rss/novice",
    "Pod črto": "https://pod-crto.si/feed/",
    "MIA": "https://mia.mk/rss/",
    "Dan": "https://www.dan.co.me/rss",
    "RTK": "https://www.rtklive.com/sq/feed/",
    "Kathimerini": "https://www.kathimerini.gr/rss/",
    "Efimerida ton Syntakton": "https://www.efsyn.gr/rss",
    "Documento": "https://www.documento.gr/feed/",
    "CyBC": "https://www.cybc.com.cy/rss",
    "MaltaToday": "https://www.maltatoday.com.mt/rss.xml",
    "Delfi Estonia": "https://www.delfi.ee/rss/uudised/",
    "Eesti Päevaleht": "https://epl.delfi.ee/rss/",
    "Siena": "https://siena.lt/feed/",
    "Mtavari Arkhi": "https://mtavari.tv/feed",
    "GPB (Georgian Public Broadcasting)": "https://1tv.ge/rss/",
    "Armenian Public TV": "https://www.1tv.am/rss",
    "Nasha Niva": "https://nashaniva.com/feed",
    "Channel One / Perviy Kanal": "https://www.1tv.ru/rss/",
    "iStories (Важные истории)": "https://istories.media/feed/",
    "The Paper (Pengpai)": "https://www.thepaper.cn/rss_promotion.jsp",
    "The Standard (HK)": "https://www.thestandard.com.hk/rss_news.php",
    "RTHK": "https://news.rthk.hk/rthk/en/rss/",
    "Ming Pao": "https://www.mingpao.com/rss/mingpaonews.xml",
    "United Daily News": "https://udn.com/rssfeed/news/2/LANG/1/RSS.XML",
    "China Times": "https://www.chinatimes.com/rss/",
    "The Reporter (報導者)": "https://www.twreporter.org/api/v2/index_page/news?format=rss",
    "CommonWealth Magazine": "https://www.cw.com.tw/rss/",
    "The Yomiuri Shimbun": "https://www.yomiuri.co.jp/rss/",
    "Nikkei (Nihon Keizai Shimbun)": "https://www.nikkei.com/rss/",
    "Sankei Shimbun": "https://www.sankei.com/rss/",
    "Kyodo News": "https://english.kyodonews.net/rss/all.xml",
    "Jiji Press": "https://www.jiji.com/rss/",
    "Tokyo Shimbun": "https://www.tokyo-np.co.jp/list/rss/all.rss",
    "Tōyō Keizai": "https://toyokeizai.net/list/rss/business",
    "JoongAng Ilbo": "https://www.joongang.co.kr/RSS/joongang.xml",
    "Kyunghyang Shinmun": "https://www.khan.co.kr/rss/rssdata/kh_rss.xml",
    "MBC": "https://imnews.imbc.com/rss/",
    "SBS": "https://news.sbs.co.kr/news/rss/",
    "TODAY (SG)": "https://www.todayonline.com/rss",
    "The Star (MY)": "https://www.thestar.com.my/rss/News",
    "The Edge": "https://www.theedgemarkets.com/rss",
    "Tempo": "https://tempo.co/rss",
    "Koran Tempo": "https://koran.tempo.co/feed/",
    "ABS-CBN": "https://news.abs-cbn.com/rss/news",
    "The Nation (Thailand)": "https://www.nationthailand.com/rss-feeds",
    "Thai PBS": "https://www.thaipbs.or.th/rss",
    "The Standard (TH)": "https://www.thestandard.co.th/feed",
    "Manager Daily": "https://mgronline.com/rss/",
    "VietnamNet": "https://vietnamnet.vn/rss/",
    "VNA (Vietnam News Agency)": "https://en.vietnamplus.vn/rss/home.rss",
    "VOD (Voice of Democracy)": "https://vod.com.kh/feed/",
    "KPL (Lao News Agency)": "https://kpl.net.la/en/rss",
    "Borneo Bulletin": "https://borneobulletin.com.bn/feed/",
    "Tempo Timor": "https://tempotimor.com/feed/",
    "The News International": "https://www.thenews.com.pk/rss/",
    "bdnews24.com": "https://bdnews24.com/rss/",
    "New Age (BD)": "https://www.newagebd.net/rss.php",
    "Daily Mirror (LK)": "https://www.dailymirror.lk/rss",
    "Lankadeepa": "https://www.lankadeepa.lk/rss",
    "Tamil Mirror": "https://www.tamizmirror.lk/feed/",
    "Republica": "https://myrepublica.nagariknetwork.com/feed/",
    "Online Khabar": "https://www.onlinekhabar.com/feed",
    "Hasht-e Subh": "https://8am.af/rss/",
    "Kuensel": "https://kuenselonline.com/feed/",
    "Maldives Independent": "https://maldivesindependent.com/feed/",
    "Raajje.mv": "https://raajje.mv/rss",
    "Kazakh TV / Khabar": "https://www.khabar.kz/rss",
    "Mediazona Central Asia": "https://centralasia.mediazona.ca/rss/",
    "Hürriyet": "https://www.hurriyet.com.tr/rss/anasayfa",
    "Ahval News": "https://ahvalnews.com/en/rss.xml",
    "TRT World": "https://www.trtworld.com/rss.xml",
    "Duvar": "https://www.gazeteduvar.com.tr/feed/",
    "Israel Hayom": "https://www.israelhayom.com/feed/",
    "Kan": "https://www.kan.org.il/rss/",
    "Channel 12 / 13 / 14": "https://www.mako.co.il/rss/news",
    "Mako / N12": "https://www.mako.co.il/rss/news",
    "Walla!": "https://rss.walla.co.il/feed/22",
    "Local Call (Sikha Mekomit)": "https://www.mekomit.co.il/feed/",
    "Ma'an News": "https://www.maannews.net/rss.aspx",
    "L'Orient-Le Jour": "https://today.lorientlejour.com/feed",
    "The Daily Star (Lebanon)": "https://www.dailystar.com.lb/rss.aspx",
    "Al-Akhbar": "https://al-akhbar.com/rss",
    "Al Manar": "https://www.almanar.com.lb/rss",
    "MTV Lebanon": "https://www.mtv.com.lb/rss",
    "Daraj": "https://daraj.com/feed/",
    "Megaphone": "https://www.megaphone.news/feed",
    "Al Ghad": "https://alghad.com/feed/",
    "Petra (JNA)": "https://petra.gov.jo/rss.aspx",
    "7iber": "https://7iber.com/feed/",
    "NRT": "https://www.nrttv.com/en/rss/",
    "Iraq Oil Report": "https://www.iraqoilreport.com/feed/",
    "Kirkuk Now": "https://kirkuknow.com/en/feed/",
    "Shargh": "https://sharghdaily.com/rss",
    "Kayhan": "https://kayhan.ir/rss",
    "Manoto": "https://manoto.com/rss",
    "SPA (Saudi Press Agency)": "https://www.spa.gov.sa/rss/latest_news.xml",
    "Al Riyadh": "https://www.alriyadh.com/rss/home",
    "The National (UAE)": "https://www.thenationalnews.com/rss",
    "Gulf News": "https://gulfnews.com/cms/rss/news.xml",
    "Khaleej Times": "https://www.khaleejtimes.com/rss/news",
    "WAM (Emirates News Agency)": "https://wam.ae/en/rss",
    "Al Ain News": "https://www.alainnews.ae/rss",
    "The Peninsula": "https://www.thepeninsulaqatar.com/rss.xml",
    "Kuwait Times": "https://news.kuwaittimes.net/feed/",
    "Al-Qabas": "https://www.alqabas.com/rss/",
    "Gulf Daily News": "https://www.gdnonline.com/rss",
    "BNA": "https://www.bna.bh/rss/",
    "ONA (Oman News Agency)": "https://onaofficial.com/rss",
    "Times of Oman": "https://www.timesofoman.com/rss",
    "Saba (Yemen News Agency)": "https://www.sabanews.net/en/rss",
    "Belqees TV": "https://www.belqeestv.com/rss",
    "The Syria Report": "https://www.syria-report.com/rss",
    "Al-Ahram": "https://english.ahram.org.eg/rss/",
    "Al-Masry Al-Youm": "https://www.almasryalyoum.com/rss/",
    "MENA (Middle East News Agency)": "https://www.mena.org.eg/rss",
    "Libya Observer": "https://www.libyaobserver.ly/feed/",
    "LANA": "https://lana.gov.ly/rss",
    "Meshkal": "https://meshkal.com/feed/",
    "APS (Algeria)": "https://www.aps.dz/rss.xml",
    "Le360": "https://le360.ma/feed/",
    "MAP": "https://www.mapnews.ma/rss",
    "Vanguard (NG)": "https://www.vanguardngr.com/feed/",
    "The Guardian (Nigeria)": "https://guardian.ng/feed/",
    "NAN (News Agency of Nigeria)": "https://www.nan.ng/feed/",
    "FIJ (Foundation for Investigative Journalism)": "https://fij.ng/feed/",
    "Daily Graphic": "https://www.graphic.com.gh/feed/",
    "MyJoyOnline": "https://www.myjoyonline.com/feed/",
    "GNA (Ghana News Agency)": "https://www.ghananewsagency.org/rss",
    "Le Soleil (Senegal)": "https://www.lesoleil.sn/feed/",
    "APS (Agence de Presse Sénégalaise)": "https://www.aps.sn/rss/",
    "L'Observateur Paalga": "https://lobservateur.bf/feed/",
    "AIB": "https://www.aib.bf/rss/",
    "Malijet": "https://malijet.com/rss",
    "L'Essor": "https://www.essor.ml/rss",
    "Actuniger": "https://www.actuniger.com/feed/",
    "ANP (Niger)": "https://www.anp.ne/rss",
    "Daily Observer (Liberia)": "https://www.liberianobserver.com/feed",
    "The Standard (Gambia)": "https://thestandard.gm/feed/",
    "La Nation (Benin)": "https://www.lanation.bj/feed/",
    "A Semana": "https://www.asemana.publ.cv/spip.php?page=backend",
    "AMI (Mauritania)": "https://ami.mr/rss",
    "The Star (Kenya)": "https://www.the-star.co.ke/rss/",
    "Business Daily Africa": "https://www.businessdailyafrica.com/rss/",
    "Citizen TV": "https://www.citizentv.co.ke/feed/",
    "ENA (Ethiopian News Agency)": "https://www.ena.et/rss/",
    "Fana Broadcasting": "https://www.fanabc.com/feed/",
    "TBC (Tanzania Broadcasting Corp)": "https://www.tbc.go.tz/rss/",
    "NBS Television": "https://www.nbswebsite.com/feed/",
    "RNA": "https://www.rnanews.com/rss",
    "ABP (Burundi)": "https://www.abpinfos.com/feed/",
    "Dalsan Radio": "https://dalsanmedia.com/feed/",
    "SONNA": "https://sonna.so/feed/",
    "Eye Radio": "https://www.eyeradio.org/feed/",
    "Radio Tamazuj": "https://radiotamazuj.org/en/rss.xml",
    "Asmarino": "https://asmarino.com/feed/",
    "HZK Press": "https://hzk-press.com/feed/",
    "City Press": "https://www.news24.com/citypress/feed",
    "The Herald (Zimbabwe)": "https://www.herald.co.zw/feed/",
    "Zambia Daily Nation": "https://www.zambiandailynation.com/feed/",
    "MANA": "https://www.manaonline.gov.mw/rss",
    "BOPA": "https://bopa.gov.bw/rss",
    "The Voice (Botswana)": "https://www.thevoicebw.com/feed/",
    "New Era (Namibia)": "https://neweralive.na/feed/",
    "Jornal de Angola": "https://www.jornaldeangola.ao/rss.xml",
    "Club-K": "https://club-k.net/rss",
    "ACP (DRC)": "https://www.acpcongo.com/rss",
    "ACI (Congo)": "https://www.aci-media.net/rss",
    "Les Dépêches de Brazzaville": "https://www.adiac-congo.com/rss.xml",
    "Cameroon Tribune": "https://www.cameroon-tribune.cm/rss",
    "The Post (Cameroon)": "https://www.postwebcam.com/feed/",
    "L'Union (Gabon)": "https://www.union.sonapresse.com/rss",
    "ASONGA": "https://asonga.gq/feed/",
    "ATPE": "https://www.atcpmedia.td/rss",
    "ACAP": "https://radiotelecentrafrique.com/rss",
    "Tela Nón": "https://telanon.net/feed/",
    "The Africa Report": "https://www.theafricareport.com/feed/",
    "African Business": "https://african.business/feed/",
    "The Monthly": "https://www.themonthly.com.au/rss",
    "The Conversation (AU)": "https://theconversation.com/au/feed",
    "Newsroom (NZ)": "https://www.newsroom.co.nz/feed/",
    "NZPA / AAP NZ": "https://www.aap.com.au/feed/",
    "Samoa Observer": "https://www.samoaobserver.ws/feed/",
    "Pacific Islands News Association (PINA)": "https://pina.com.fj/feed/",
    "Asia Pacific Report": "https://asiapacificreport.nz/feed/",
    "Ground News": "https://ground.news/rss",
    # ── Final batch ───────────────────────────────────────────────────────────
    "TODAY (SG)": "https://www.todayonline.com/rss",
    "The Star (MY)": "https://www.thestar.com.my/rss/News",
    "Tirto.id": "https://tirto.id/rss",
    "IDL-Reporteros": "https://idl-reporteros.pe/feed/",
    "New Age (BD)": "https://www.newagebd.net/rss.php",
    "Vanguard (NG)": "https://www.vanguardngr.com/feed/",
    "Le Soleil": "https://www.lesoleil.sn/feed/",
    "Newsroom (NZ)": "https://www.newsroom.co.nz/feed/",
    "El Nacional (VE)": "https://www.elnacional.com/feed/",
    "MTI": "https://www.mti.hu/rss",
    "Capital (BG)": "https://www.capital.bg/rss/",
    "Dnevnik (BG)": "https://www.dnevnik.bg/rss/",
    "Dnevnik (SI)": "https://www.dnevnik.si/rss/novice",
    "APA (Azerbaijan)": "https://en.apa.az/rss",
    "AzTV": "https://aztv.az/rss",
    "AyiboPost": "https://ayibopost.com/feed/",
    "Trinidad Express": "https://trinidadexpress.com/feed/",
    "Montsame": "https://montsame.mn/en/rss",
    "UB Post": "https://theubposts.com/feed/",
    "BSS (Bangladesh Sangbad Sangstha)": "https://www.bssnews.net/rss/",
    "Maldives PSM": "https://psm.mv/rss",
    "KUNA": "https://www.kuna.net.kw/rss/en",
    "ANP (Niger)": "https://www.anp.ne/rss/",
    "ABP (Burundi)": "https://www.abpinfos.com/feed/",
    "ACI (Congo)": "https://www.aci-media.net/rss",
    "L'Union (Gabon)": "https://union.sonapresse.com/rss",
    "ACP (DRC)": "https://www.acpcongo.com/rss",
    # ── Additional US ────────────────────────────────────────────────────────
    "One America News (OAN)": "https://www.oann.com/feed/",
    "Univision": "https://www.univision.com/noticias/rss",
    "Telemundo": "https://feeds.telemundo.com/rss",
    # ── Additional Latin America ─────────────────────────────────────────────
    "TV Globo": "https://g1.globo.com/rss/g1/",
    "Agência Brasil": "https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml",
    "Brasil de Fato": "https://www.brasildefato.com.br/feeds/rss/en",
    "Jovem Pan": "https://jovempan.com.br/feed",
    "El Destape": "https://www.eldestapeweb.com/rss.xml",
    "La Derecha Diario": "https://www.laDerechaDiario.com.ar/feed/",
    "Cuestión Pública": "https://cuestionpublica.com/feed/",
    "La Silla Vacía": "https://lasillavacia.com/feed/",
    "TeleSUR": "https://www.telesurtv.net/rss/",
    "El Nacional (VE)": "https://www.elnacional.com/feed/",
    "Página Siete": "https://www.paginasiete.bo/rss/",
    "El Surtidor": "https://www.elsurtidor.com/feed/",
    "El Observador (UY)": "https://www.elobservador.com.uy/rss.xml",
    "Reforma": "https://www.reforma.com/rss/portada.xml",
    # ── Additional Europe ────────────────────────────────────────────────────
    "Les Échos": "https://www.lesechos.fr/rss/rss_une.xml",
    "ZDF": "https://www.zdf.de/rss-feed.xml",
    "Tagesschau / ARD": "https://www.tagesschau.de/xml/rss2/",
    "Junge Freiheit": "https://jungefreiheit.de/feed/",
    "La Libre Belgique": "https://www.lalibre.be/arc/outboundfeeds/rss/",
    "Ara": "https://www.ara.cat/rss.xml",
    "GeenStijl": "https://www.geenstijl.nl/feeds/rss/",
    "WOZ": "https://www.woz.ch/feed",
    "Weltwoche": "https://www.weltwoche.ch/feed/",
    "Kronen Zeitung": "https://www.krone.at/rss/alle",
    "Jornal de Notícias": "https://www.jn.pt/rss/",
    "Lusa": "https://www.lusa.pt/rss.xml",
    "Sveriges Radio (SR)": "https://sverigesradio.se/rss/artikel/",
    "Göteborgs-Posten": "https://www.gp.se/feeds/rss/",
    "ETC": "https://www.etc.se/feed",
    "Filter": "https://filtermag.se/feed/",
    "Klassekampen": "https://www.klassekampen.no/feed/",
    "Nettavisen": "https://www.nettavisen.no/rss.xml",
    "Morgenbladet": "https://www.morgenbladet.no/feed/",
    "Zetland": "https://www.zetland.dk/rss",
    "Information": "https://www.information.dk/rss",
    "Ekstra Bladet": "https://ekstrabladet.dk/rss/",
    "Morgunblaðið": "https://www.mbl.is/feeds/rss/forsida/",
    "RÚV": "https://www.ruv.is/rss/",
    "Stundin": "https://stundin.is/feed/",
    "TVP (Telewizja Polska)": "https://tvp.info/feed",
    "OKO.press": "https://oko.press/feed/",
    "Onet": "https://wiadomosci.onet.pl/.feed",
    "Denník N": "https://dennikn.sk/feed/",
    "SME": "https://www.sme.sk/rss",
    "Aktuality.sk": "https://www.aktuality.sk/rss/",
    "Jutarnji list": "https://www.jutarnji.hr/feed",
    "Večernji list": "https://www.vecernji.hr/feeds/latest",
    "Index.hr": "https://www.index.hr/rss",
    "HRT": "https://vijesti.hrt.hr/feed/rss",
    "Telegram.hr": "https://www.telegram.hr/feed/",
    "N1": "https://n1info.com/feed/",
    "Danas": "https://www.danas.rs/feed/",
    "RTS": "https://www.rts.rs/rss/",
    "Delo": "https://www.delo.si/feed/",
    "Dnevnik (SI)": "https://www.dnevnik.si/feeds/rss/",
    "RTV Slovenija": "https://www.rtvslo.si/feed/rss",
    "Al Jazeera Balkans": "https://balkans.aljazeera.net/feed/",
    "Vijesti": "https://www.vijesti.me/rss",
    "Balkanweb": "https://www.balkanweb.com/feed/",
    "Exit.al": "https://exit.al/en/feed/",
    "Ta Nea": "https://www.tanea.gr/feed/",
    "ERT": "https://www.ert.gr/feed/",
    "Libertatea": "https://www.libertatea.ro/rss",
    "Digi24": "https://www.digi24.ro/rss",
    "HotNews.ro": "https://www.hotnews.ro/rss/",
    "G4Media": "https://www.g4media.ro/feed",
    "Dnevnik (BG)": "https://www.dnevnik.bg/rss/",
    "Mediapool": "https://www.mediapool.bg/rss",
    "BNT": "https://bnt.bg/rss/news",
    "RTVS": "https://www.rtvs.sk/rss/spravy",
    "ERR": "https://www.err.ee/rss",
    "LSM (Latvian Public Media)": "https://www.lsm.lv/rss/",
    "LRT": "https://www.lrt.lt/rss.xml",
    "Hromadske": "https://hromadske.ua/rss",
    "NV (Novoye Vremya)": "https://nv.ua/rss/all.xml",
    "UNIAN": "https://www.unian.info/rss/all.rss",
    "Suspilne": "https://suspilne.media/rss",
    "Civil.ge": "https://civil.ge/feed",
    "Civilnet": "https://www.civilnet.am/feed/",
    "Novaya Gazeta": "https://novayagazeta.ru/rss/all.xml",
    "Mediazona": "https://zona.media/rss",
    "RT (Russia Today)": "https://www.rt.com/rss/",
    "Vedomosti": "https://www.vedomosti.ru/rss/news",
    "Interfax": "https://www.interfax.ru/rss.asp",
    "Kommersant": "https://www.kommersant.ru/RSS/news.xml",
    "SRF / RTS / RSI": "https://www.srf.ch/news/bnf/rss/1890-LATEST",
    # ── Additional Asia ──────────────────────────────────────────────────────
    "The Jakarta Post": "https://www.thejakartapost.com/feed/",
    "Detik.com": "https://rss.detik.com/index.php/detik_news",
    "Antara": "https://en.antaranews.com/rss/topstories.rss",
    "The Economic Times": "https://economictimes.indiatimes.com/rssfeedsdefault.cms",
    "Republic TV": "https://www.republicworld.com/rss/",
    "Times Now": "https://www.timesnownews.com/rss",
    "India Today": "https://www.indiatoday.in/rss/home",
    "The Quint": "https://www.thequint.com/feed",
    "Newslaundry": "https://www.newslaundry.com/feed",
    "OpIndia": "https://www.opindia.com/feed/",
    "Swarajya": "https://swarajyamag.com/feed",
    "PTI (Press Trust of India)": "https://feeds.ptinews.com/rss/pti_news.xml",
    "Dainik Jagran": "https://www.jagran.com/rss/news-national.xml",
    "Amar Ujala": "https://www.amarujala.com/feed/breaking-news.xml",
    "Dainik Bhaskar": "https://www.bhaskar.com/rss-feed/1061/",
    "The News Minute": "https://www.thenewsminute.com/feed",
    "Alt News": "https://www.altnews.in/feed/",
    "APP (Associated Press of Pakistan)": "https://www.app.com.pk/feed/",
    "New Age (BD)": "https://www.newagebd.net/rss.php",
    "Groundviews": "https://groundviews.org/feed/",
    "Online Khabar": "https://www.onlinekhabar.com/feed",
    "Prachatai": "https://prachatai.com/feed",
    "Khaosod English": "https://www.khaosodenglish.com/feed/",
    "TOLOnews": "https://tolonews.com/rss.xml",
    "Pajhwok Afghan News": "https://www.pajhwok.com/en/rss.xml",
    "The Irrawaddy": "https://www.irrawaddy.com/feed",
    "Myanmar Now": "https://myanmar-now.org/en/feed/",
    "Mizzima": "https://mizzima.com/feed",
    "Democratic Voice of Burma (DVB)": "https://english.dvb.no/feed/",
    "CamboJA": "https://cambojanews.com/feed/",
    "Phnom Penh Post": "https://www.phnompenhpost.com/rss.xml",
    "Civil.ge": "https://civil.ge/feed",
    "Tengrinews": "https://tengrinews.kz/rss/",
    "Vlast.kz": "https://vlast.kz/rss/",
    "Gazeta.uz": "https://www.gazeta.uz/rss/",
    "Kun.uz": "https://kun.uz/rss",
    "Asia-Plus": "https://www.asiaplustj.info/rss.xml",
    "Kloop": "https://kloop.kg/feed/",
    "Kaktus Media": "https://kaktus.media/rss",
    "The Straits Times": "https://www.straitstimes.com/news/world/rss.xml",
    "Today (SG)": "https://www.todayonline.com/feed",
    "Mothership": "https://mothership.sg/feed/",
    "Lianhe Zaobao": "https://www.zaobao.com.sg/rss/singapore",
    "The Star (MY)": "https://www.thestar.com.my/rss/news/",
    "Free Malaysia Today": "https://www.freemalaysiatoday.com/feed/",
    "Utusan Malaysia": "https://www.utusan.com.my/feed/",
    "Sinar Harian": "https://www.sinarharian.com.my/feed/",
    "CNA (Central News Agency)": "https://www.cna.com.tw/rss/aall.aspx",
    "Taipei Times": "https://www.taipeitimes.com/rss",
    "Liberty Times": "https://www.ltn.com.tw/rss/news.xml",
    "Chosun Ilbo": "https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml",
    "KBS": "https://world.kbs.co.kr/rss/rss_english.htm",
    "Yonhap News": "https://en.yna.co.kr/RSS/news.xml",
    "Newstapa": "https://newstapa.org/feed",
    "Anadolu Agency (AA)": "https://www.aa.com.tr/en/rss/default.rss",
    "Rudaw": "https://www.rudaw.net/rss",
    "IRNA": "https://en.irna.ir/rss",
    "Radio Farda / RFE": "https://www.radiofarda.com/api/zpqoveltk",
    "Yedioth Ahronoth / Ynet": "https://www.ynet.co.il/Integration/StoryRss2.xml",
    "WAFA": "http://www.wafa.ps/rss.aspx?id=206",
    "Syria Direct": "https://syriadirect.org/feed/",
    "Mada Masr": "https://www.madamasr.com/en/feed/",
    "Daily News Egypt": "https://www.dailynewsegypt.com/feed/",
    "Al-Masdar Online": "https://almasdaronline.com/feed/",
    "Nawaat": "https://nawaat.org/feed/",
    "TSA (Tout Sur l'Algérie)": "https://www.tsa-algerie.com/feed/",
    "El Watan": "https://www.elwatan.com/feed/",
    "Hespress": "https://www.hespress.com/feed",
    "Le Desk": "https://ledesk.ma/feed/",
    # ── Additional Africa ────────────────────────────────────────────────────
    "Vanguard (NG)": "https://www.vanguardngr.com/feed/",
    "Channels Television": "https://www.channelstv.com/feed/",
    "ThisDay": "https://www.thisdaylive.com/index.php/feed/",
    "Daily Trust": "https://dailytrust.com/feed",
    "Sahara Reporters": "https://saharareporters.com/feed/",
    "The Cable": "https://www.thecable.ng/feed",
    "Citi FM/Newsroom": "https://citinewsroom.com/feed/",
    "Joy Online / JoyFM": "https://www.myjoyonline.com/feed/",
    "The Fourth Estate": "https://4thestategh.com/feed/",
    "Seneweb": "https://www.seneweb.com/rss",
    "FrontPageAfrica": "https://frontpageafricaonline.com/feed/",
    "Awoko": "https://awoko.org/feed/",
    "The Elephant (KE)": "https://www.theelephant.info/feed/",
    "KTN News": "https://www.ktnnews.com/feed/",
    "Africa Uncensored": "https://africauncensored.online/feed/",
    "Addis Standard": "https://addisstandard.com/feed/",
    "Ethiopian Reporter": "https://www.ethiopianreporter.com/feed/",
    "Borkena": "https://borkena.com/feed/",
    "Daily Monitor": "https://www.monitor.co.ug/monitor/rss/",
    "New Vision": "https://www.newvision.co.ug/rss",
    "The Observer (Uganda)": "https://observer.ug/feed",
    "The New Times (Rwanda)": "https://www.newtimes.co.rw/rss.xml",
    "IWACU": "https://www.iwacu-burundi.org/feed/",
    "Garowe Online": "https://www.garoweonline.com/en/rss/",
    "Eye Radio": "https://www.eyeradio.org/feed/",
    "Maka Angola": "https://makaangola.org/feed/",
    "Radio Okapi": "https://www.radiookapi.net/rss.xml",
    "Actualité.cd": "https://actualite.cd/feed",
    "Le Jour": "https://www.quotidienlejour.com/feed/",
    "L'Express (Mauritius)": "https://lexpress.mu/feed",
    "Le Mauricien": "https://lemauricien.com/feed/",
    "L'Express de Madagascar": "https://www.lexpress.mg/feed",
    "ZimLive": "https://www.zimlive.com/feed/",
    "NewsDay (Zimbabwe)": "https://www.newsday.co.zw/feed/",
    "The Zimbabwe Independent": "https://theindependent.co.zw/feed/",
    "The Mast": "https://www.themastonline.com/feed/",
    "The Nation (Malawi)": "https://mwnation.com/feed/",
    "Malawi24": "https://malawi24.com/feed/",
    "Mmegi": "https://www.mmegi.bw/rss",
    "The Namibian": "https://www.namibian.com.na/rss/",
    "Lesotho Times": "https://www.lestimes.com/feed/",
    "Maka Angola": "https://makaangola.org/feed/",
    "TimesLIVE": "https://www.timeslive.co.za/rss/",
    "Business Day": "https://www.businesslive.co.za/rss/",
    "EWN (Eyewitness News)": "https://ewn.co.za/Feed",
    "GroundUp": "https://groundup.org.za/feed/",
    "amaBhungane": "https://amabhungane.org/feed/",
    "Sowetan": "https://www.sowetanlive.co.za/rss/",
    "Africa Report": "https://www.theafricareport.com/feed/",
    "Jeune Afrique": "https://www.jeuneafrique.com/feed/",
    "African Arguments": "https://africanarguments.org/feed/",
    "The Continent": "https://thecontinent.org/feed/",
    # ── Additional Oceania ───────────────────────────────────────────────────
    "The Australian Financial Review": "https://www.afr.com/rss",
    "Crikey": "https://www.crikey.com.au/feed/",
    "AAP (Australian Associated Press)": "https://www.aap.com.au/feed/",
    "Newsroom (NZ)": "https://www.newsroom.co.nz/feed/",
    "The Spinoff": "https://thespinoff.co.nz/feed/",
    "TVNZ / 1News": "https://www.1news.co.nz/rss",
    "Fiji Times": "https://www.fijitimes.com.fj/feed/",
    "Matangi Tonga": "https://matangitonga.to/feed",
    "Vanuatu Daily Post": "https://www.dailypost.vu/feed/",
    "Solomon Star": "https://www.solomonstarnews.com/feed/",
    "RNZ Pacific": "https://www.rnz.co.nz/international/pacific-news/rss.xml",
    # ── Additional Global ────────────────────────────────────────────────────
    "RT": "https://www.rt.com/rss/",
    "TeleSUR": "https://www.telesurtv.net/rss/",
    "The Diplomat": "https://thediplomat.com/feed/",
    "Rest of World": "https://restofworld.org/feed/",
    "ICIJ": "https://www.icij.org/feed/",
    "Global Voices": "https://globalvoices.org/feed/",
    "The Conversation": "https://theconversation.com/us/feeds",
    "SABC News": "https://www.sabcnews.com/sabcnews/feed/",
    "Quartz Africa": "https://qz.com/africa/feed/",
}

# ---------------------------------------------------------------------------
# Base URLs for auto-discovery (source name → home page URL)
# ---------------------------------------------------------------------------
BASE_URLS: dict[str, str] = {
    # Filling in base URLs for sources not in KNOWN_RSS
    "La Presse": "https://www.lapresse.ca",
    "Le Devoir": "https://www.ledevoir.com",
    "iPolitics": "https://www.ipolitics.ca",
    "Western Standard": "https://www.westernstandard.news",
    "El Universal (MX)": "https://www.eluniversal.com.mx",
    "Reforma": "https://www.reforma.com",
    "Televisa / N+": "https://noticieros.televisa.com",
    "TV Azteca": "https://www.tvazteca.com/aztecanoticias",
    "Nexos": "https://www.nexos.com.mx",
    "Prensa Libre": "https://www.prensalibre.com",
    "Nómada": "https://nomada.gt",
    "El Heraldo": "https://www.elheraldo.hn",
    "La Prensa (Honduras)": "https://www.laprensa.hn",
    "Contracorriente": "https://contracorriente.red",
    "El Diario de Hoy": "https://www.elsalvador.com",
    "La Prensa Gráfica": "https://www.laprensagrafica.com",
    "El Faro": "https://elfaro.net",
    "Confidencial": "https://confidencial.digital",
    "La Nación (CR)": "https://www.nacion.com",
    "La Prensa (Panama)": "https://www.prensa.com",
    "14ymedio": "https://www.14ymedio.com",
    "Listín Diario": "https://listindiario.com",
    "Le Nouvelliste": "https://lenouvelliste.com",
    "The Gleaner": "https://jamaica-gleaner.com",
    "Jamaica Observer": "https://www.jamaicaobserver.com",
    "TV Globo": "https://g1.globo.com",
    "Revista Piauí": "https://piaui.folha.uol.com.br",
    "Jovem Pan": "https://jovempan.com.br",
    "La Silla Vacía": "https://lasillavacia.com",
    "Caracol TV/Radio": "https://www.caracoltv.com",
    "RCN": "https://www.rcnradio.com",
    "CIPER Chile": "https://ciperchile.cl",
    "The Clinic": "https://www.theclinic.cl",
    "Interferencia": "https://interferencia.cl",
    "Ex-Ante": "https://www.ex-ante.cl",
    "IDL-Reporteros": "https://idl-reporteros.pe",
    "Ojo Público": "https://ojo-publico.com",
    "El Nacional (VE)": "https://www.elnacional.com",
    "El Universal (VE)": "https://www.eluniversal.com",
    "Efecto Cocuyo": "https://efectococuyo.com",
    "Runrun.es": "https://runrun.es",
    "Tal Cual": "https://talcualdigital.com",
    "El Universo": "https://www.eluniverso.com",
    "El Comercio (EC)": "https://www.elcomercio.com",
    "GK (formerly GkillCity)": "https://gk.city",
    "Plan V": "https://www.planv.com.ec",
    "El Deber": "https://eldeber.com.bo",
    "Los Tiempos": "https://www.lostiempos.com",
    "ABC Color": "https://www.abc.com.py",
    "Última Hora": "https://www.ultimahora.com",
    "El País (UY)": "https://www.elpais.com.uy",
    "La Diaria": "https://ladiaria.com.uy",
    "El Observador (UY)": "https://www.elobservador.com.uy",
    "Private Eye": "https://www.private-eye.co.uk",
    "The Canary": "https://www.thecanary.co",
    "Novara Media": "https://novaramedia.com",
    "Les Échos": "https://www.lesechos.fr",
    "Valeurs Actuelles": "https://www.valeursactuelles.com",
    "CNews": "https://www.cnews.fr",
    "Tagesschau / ARD": "https://www.tagesschau.de",
    "ZDF": "https://www.zdf.de",
    "Junge Freiheit": "https://www.junge-freiheit.de",
    "Il Giornale": "https://www.ilgiornale.it",
    "Libero": "https://www.liberoquotidiano.it",
    "Il Manifesto": "https://ilmanifesto.it",
    "Público (ES)": "https://www.publico.es",
    "Libertad Digital": "https://www.libertaddigital.com",
    "OKDiario": "https://okdiario.com",
    "Ara": "https://www.ara.cat",
    "Follow the Money": "https://www.ftm.nl",
    "GeenStijl": "https://www.geenstijl.nl",
    "La Libre Belgique": "https://www.lalibre.be",
    "Apache": "https://www.apache.be",
    "Knack": "https://www.knack.be",
    "Le Temps": "https://www.letemps.ch",
    "WOZ": "https://www.woz.ch",
    "Weltwoche": "https://www.weltwoche.ch",
    "Kronen Zeitung": "https://www.krone.at",
    "Falter": "https://www.falter.at",
    "eXXpress": "https://www.exxpress.at",
    "Jornal de Notícias": "https://www.jn.pt",
    "Lusa": "https://www.lusa.pt",
    "Gript": "https://gript.ie",
    "Aftonbladet": "https://www.aftonbladet.se",
    "Expressen": "https://www.expressen.se",
    "Sveriges Radio (SR)": "https://sverigesradio.se",
    "Göteborgs-Posten": "https://www.gp.se",
    "ETC": "https://www.etc.se",
    "Nya Tider": "https://www.nyatider.nu",
    "Filter": "https://filtermag.se",
    "Dagbladet": "https://www.dagbladet.no",
    "Klassekampen": "https://www.klassekampen.no",
    "Nettavisen": "https://www.nettavisen.no",
    "Morgenbladet": "https://www.morgenbladet.no",
    "Zetland": "https://www.zetland.dk",
    "Information": "https://www.information.dk",
    "Ekstra Bladet": "https://ekstrabladet.dk",
    "Ilta-Sanomat": "https://www.is.fi",
    "Iltalehti": "https://www.iltalehti.fi",
    "Hufvudstadsbladet": "https://www.hbl.fi",
    "Long Play": "https://www.longplay.fi",
    "Morgunblaðið": "https://www.mbl.is",
    "RÚV": "https://www.ruv.is",
    "Stundin": "https://stundin.is",
    "Rzeczpospolita": "https://www.rp.pl",
    "TVN24": "https://tvn24.pl",
    "TVP (Telewizja Polska)": "https://tvp.info",
    "Newsweek Polska": "https://www.newsweek.pl",
    "Do Rzeczy": "https://dorzeczy.pl",
    "wSieci / wPolityce": "https://wpolityce.pl",
    "OKO.press": "https://oko.press",
    "Onet": "https://wiadomosci.onet.pl",
    "Krytyka Polityczna": "https://krytykapolityczna.pl",
    "Deník N": "https://denikn.cz",
    "Respekt": "https://www.respekt.cz",
    "iDNES.cz": "https://www.idnes.cz",
    "Aktuálně.cz": "https://aktualne.cz",
    "Parlamentní listy": "https://www.parlamentnilisty.cz",
    "Česká televize (ČT)": "https://ct24.ceskatelevize.cz",
    "444.hu": "https://444.hu",
    "HVG": "https://hvg.hu",
    "Index.hu": "https://index.hu",
    "Magyar Nemzet": "https://magyarnemzet.hu",
    "Origo.hu": "https://www.origo.hu",
    "Átlátszó": "https://atlatszo.hu",
    "Direkt36": "https://www.direkt36.hu",
    "Libertatea": "https://www.libertatea.ro",
    "Digi24": "https://www.digi24.ro",
    "Recorder": "https://recorder.ro",
    "HotNews.ro": "https://www.hotnews.ro",
    "România Liberă": "https://romanialibera.ro",
    "Rise Project": "https://www.riseproject.ro",
    "G4Media": "https://www.g4media.ro",
    "Capital (BG)": "https://www.capital.bg",
    "Dnevnik (BG)": "https://www.dnevnik.bg",
    "Mediapool": "https://www.mediapool.bg",
    "Bivol": "https://bivol.bg",
    "BNT": "https://bnt.bg",
    "Denník N": "https://dennikn.sk",
    "SME": "https://www.sme.sk",
    "Aktuality.sk": "https://www.aktuality.sk",
    "RTVS": "https://www.rtvs.sk",
    "Jutarnji list": "https://www.jutarnji.hr",
    "Večernji list": "https://www.vecernji.hr",
    "Index.hr": "https://www.index.hr",
    "HRT": "https://www.hrt.hr",
    "Telegram.hr": "https://www.telegram.hr",
    "N1": "https://n1info.com",
    "Danas": "https://www.danas.rs",
    "Informer": "https://www.informer.rs",
    "RTS": "https://www.rts.rs",
    "KRIK": "https://www.krik.rs",
    "Delo": "https://www.delo.si",
    "Dnevnik (SI)": "https://www.dnevnik.si",
    "RTV Slovenija": "https://www.rtvslo.si",
    "Nova24TV": "https://nova24tv.si",
    "Pod črto": "https://pod-crto.si",
    "Dnevni Avaz": "https://avaz.ba",
    "Oslobođenje": "https://www.oslobodjenje.ba",
    "Al Jazeera Balkans": "https://balkans.aljazeera.net",
    "Vijesti": "https://www.vijesti.me",
    "Dan": "https://www.dan.co.me",
    "Reporter.al": "https://www.reporter.al",
    "Balkanweb": "https://www.balkanweb.com",
    "Exit.al": "https://exit.al",
    "Koha Ditore": "https://www.koha.net",
    "Kallxo.com": "https://kallxo.com",
    "RTK": "https://www.rtklive.com",
    "Kathimerini": "https://www.kathimerini.gr",
    "Ta Nea": "https://www.tanea.gr",
    "ERT": "https://www.ert.gr",
    "Proto Thema": "https://www.protothema.gr",
    "Inside Story": "https://insidestory.gr",
    "Documento": "https://www.documento.gr",
    "Phileleftheros": "https://www.philenews.com",
    "CyBC": "https://www.cybc.com.cy",
    "Times of Malta": "https://timesofmalta.com",
    "The Shift News": "https://theshiftnews.com",
    "MaltaToday": "https://www.maltatoday.com.mt",
    "Postimees": "https://www.postimees.ee",
    "Delfi Estonia": "https://www.delfi.ee",
    "ERR": "https://www.err.ee",
    "Eesti Päevaleht": "https://epl.delfi.ee",
    "Delfi Latvia": "https://www.delfi.lv",
    "LSM (Latvian Public Media)": "https://www.lsm.lv",
    "IR": "https://ir.lv",
    "Re:Baltica": "https://rebaltica.lv",
    "Delfi Lithuania": "https://www.delfi.lt",
    "15min.lt": "https://www.15min.lt",
    "LRT": "https://www.lrt.lt",
    "Siena": "https://siena.lt",
    "Hromadske": "https://hromadske.ua",
    "NV (Novoye Vremya)": "https://nv.ua",
    "UNIAN": "https://www.unian.info",
    "Babel": "https://babel.ua",
    "ZN.UA (Dzerkalo Tyzhnia)": "https://zn.ua",
    "Suspilne": "https://suspilne.media",
    "ZdG (Ziarul de Gardă)": "https://www.zdg.md",
    "NewsMaker": "https://newsmaker.md",
    "TV8": "https://tv8.md",
    "Mtavari Arkhi": "https://mtavari.tv",
    "On.ge": "https://on.ge",
    "Imedi TV": "https://imedi.ge",
    "GPB (Georgian Public Broadcasting)": "https://1tv.ge",
    "Civilnet": "https://www.civilnet.am",
    "Hetq": "https://hetq.am",
    "Armenian Public TV": "https://www.1tv.am",
    "Meydan TV": "https://www.meydan.tv",
    "OCCRP (Azerbaijani coverage)": "https://www.occrp.org",
    "Nasha Niva": "https://nashaniva.com",
    "NEXTA": "https://nexta.tv",
    "Zerkalo.io": "https://zerkalo.io",
    "Novaya Gazeta": "https://novayagazeta.ru",
    "Mediazona": "https://mediazona.ca",
    "iStories (Важные истории)": "https://istories.media",
    "Kommersant": "https://www.kommersant.ru",
    "The Paper (Pengpai)": "https://www.thepaper.cn",
    "China Daily": "https://www.chinadaily.com.cn",
    "CCTV": "https://english.cctv.com",
    "The Standard (HK)": "https://www.thestandard.com.hk",
    "RTHK": "https://news.rthk.hk",
    "Ming Pao": "https://www.mingpao.com",
    "Liberty Times": "https://www.ltn.com.tw",
    "United Daily News": "https://udn.com",
    "China Times": "https://www.chinatimes.com",
    "CNA (Central News Agency)": "https://focustaiwan.tw",
    "The Reporter (報導者)": "https://www.twreporter.org",
    "Taipei Times": "https://www.taipeitimes.com",
    "CommonWealth Magazine": "https://www.cw.com.tw",
    "The Yomiuri Shimbun": "https://www.yomiuri.co.jp",
    "The Mainichi Shimbun": "https://mainichi.jp",
    "Nikkei (Nihon Keizai Shimbun)": "https://www.nikkei.com",
    "Sankei Shimbun": "https://www.sankei.com",
    "Kyodo News": "https://english.kyodonews.net",
    "Jiji Press": "https://www.jiji.com",
    "Tokyo Shimbun": "https://www.tokyo-np.co.jp",
    "Tōyō Keizai": "https://toyokeizai.net",
    "Chosun Ilbo": "https://www.chosun.com",
    "JoongAng Ilbo": "https://joongang.co.kr",
    "Dong-A Ilbo": "https://www.donga.com",
    "Hankyoreh": "https://www.hani.co.kr",
    "Kyunghyang Shinmun": "https://www.khan.co.kr",
    "KBS": "https://news.kbs.co.kr",
    "MBC": "https://imnews.imbc.com",
    "SBS": "https://news.sbs.co.kr",
    "Newstapa": "https://newstapa.org",
    "OhmyNews": "https://www.ohmynews.com",
    "TODAY (SG)": "https://www.todayonline.com",
    "Mothership": "https://mothership.sg",
    "The Online Citizen": "https://www.theonlinecitizen.com",
    "Lianhe Zaobao": "https://www.zaobao.com.sg",
    "The Star (MY)": "https://www.thestar.com.my",
    "New Straits Times": "https://www.nst.com.my",
    "The Edge": "https://www.theedgemarkets.com",
    "Free Malaysia Today": "https://www.freemalaysiatoday.com",
    "Utusan Malaysia": "https://www.utusan.com.my",
    "Sinar Harian": "https://www.sinarharian.com.my",
    "Tempo": "https://www.tempo.co",
    "Tirto.id": "https://tirto.id",
    "CNN Indonesia": "https://www.cnnindonesia.com",
    "Republika": "https://www.republika.co.id",
    "Koran Tempo": "https://koran.tempo.co",
    "Philippine Star": "https://www.philstar.com",
    "ABS-CBN": "https://news.abs-cbn.com",
    "GMA News": "https://www.gmanetwork.com/news",
    "Manila Bulletin": "https://mb.com.ph",
    "Manila Times": "https://www.manilatimes.net",
    "The Nation (Thailand)": "https://www.nationthailand.com",
    "Matichon": "https://www.matichon.co.th",
    "Thai PBS": "https://www.thaipbs.or.th",
    "Khaosod English": "https://www.khaosodenglish.com",
    "The Standard (TH)": "https://www.thestandard.co.th",
    "Manager Daily": "https://mgronline.com",
    "Tuổi Trẻ": "https://tuoitre.vn",
    "VietnamNet": "https://vietnamnet.vn",
    "The Irrawaddy": "https://www.irrawaddy.com",
    "Myanmar Now": "https://myanmar-now.org",
    "Mizzima": "https://mizzima.com",
    "Democratic Voice of Burma (DVB)": "https://english.dvb.no",
    "Cambodia Daily": "https://www.cambodiadaily.com",
    "Phnom Penh Post": "https://www.phnompenhpost.com",
    "CamboJA": "https://cambojanews.com",
    "The Kathmandu Post": "https://kathmandupost.com",
    "Kantipur": "https://ekantipur.com",
    "TOLOnews": "https://tolonews.com",
    "Pajhwok Afghan News": "https://pajhwok.com",
    "The News International": "https://www.thenews.com.pk",
    "Express Tribune": "https://tribune.com.pk",
    "Jang": "https://jang.com.pk",
    "ARY News": "https://arynews.tv",
    "Prothom Alo": "https://www.prothomalo.com",
    "bdnews24.com": "https://bdnews24.com",
    "Dhaka Tribune": "https://www.dhakatribune.com",
    "New Age (BD)": "https://www.newagebd.net",
    "Daily Mirror (LK)": "https://www.dailymirror.lk",
    "Groundviews": "https://groundviews.org",
    "Tengrinews": "https://tengrinews.kz",
    "Gazeta.uz": "https://www.gazeta.uz",
    "Kun.uz": "https://kun.uz",
    "Asia-Plus": "https://asiaplustj.info",
    "Cumhuriyet": "https://www.cumhuriyet.com.tr",
    "Sözcü": "https://www.sozcu.com.tr",
    "Sabah": "https://www.sabah.com.tr",
    "Yeni Şafak": "https://www.yenisafak.com",
    "Bianet": "https://bianet.org",
    "Medyascope": "https://medyascope.tv",
    "Ahval News": "https://ahvalnews.com",
    "TRT World": "https://www.trtworld.com",
    "Hürriyet": "https://www.hurriyet.com.tr",
    "Duvar": "https://www.gazeteduvar.com.tr",
    "Daily Sabah": "https://www.dailysabah.com",
    "Israel Hayom": "https://www.israelhayom.com",
    "Kan": "https://www.kan.org.il",
    "+972 Magazine": "https://www.972mag.com",
    "Ma'an News": "https://www.maannews.net",
    "Quds News Network": "https://qudsnen.co",
    "L'Orient-Le Jour": "https://today.lorientlejour.com",
    "An-Nahar": "https://www.annahar.com",
    "Al-Akhbar": "https://al-akhbar.com",
    "Daraj": "https://daraj.com",
    "The Jordan Times": "https://jordantimes.com",
    "Al Ghad": "https://alghad.com",
    "Rudaw": "https://www.rudaw.net",
    "Al-Mada": "https://almadapaper.net",
    "Shargh": "https://sharghdaily.com",
    "IranWire": "https://iranwire.com",
    "Saudi Gazette": "https://saudigazette.com.sa",
    "Asharq Al-Awsat": "https://english.aawsat.com",
    "The National (UAE)": "https://www.thenationalnews.com",
    "Gulf News": "https://gulfnews.com",
    "Khaleej Times": "https://www.khaleejtimes.com",
    "Sky News Arabia": "https://www.skynewsarabia.com",
    "The Peninsula": "https://www.thepeninsulaqatar.com",
    "Kuwait Times": "https://news.kuwaittimes.net",
    "Gulf Daily News": "https://www.gdnonline.com",
    "Times of Oman": "https://www.timesofoman.com",
    "Al-Masdar Online": "https://almasdaronline.com",
    "Belqees TV": "https://www.belqeestv.com",
    "Syria Direct": "https://syriadirect.org",
    "Enab Baladi": "https://english.enabbaladi.net",
    "Al-Ahram": "https://english.ahram.org.eg",
    "Al-Masry Al-Youm": "https://www.almasryalyoum.com",
    "Mada Masr": "https://www.madamasr.com",
    "Daily News Egypt": "https://www.dailynewsegypt.com",
    "Al-Shorouk": "https://www.shorouknews.com",
    "Libya Observer": "https://www.libyaobserver.ly",
    "Libya Herald": "https://www.libyaherald.com",
    "Nawaat": "https://nawaat.org",
    "Meshkal": "https://meshkal.com",
    "TSA (Tout Sur l'Algérie)": "https://www.tsa-algerie.com",
    "El Watan": "https://www.elwatan.com",
    "Echorouk": "https://www.echoroukonline.com",
    "TelQuel": "https://telquel.ma",
    "Le360": "https://le360.ma",
    "Medias24": "https://medias24.com",
    "Hespress": "https://www.hespress.com",
    "Le Desk": "https://ledesk.ma",
    "Vanguard (NG)": "https://www.vanguardngr.com",
    "The Guardian (Nigeria)": "https://guardian.ng",
    "Channels Television": "https://www.channelstv.com",
    "ThisDay": "https://www.thisdaylive.com",
    "Daily Trust": "https://dailytrust.com",
    "Sahara Reporters": "https://saharareporters.com",
    "The Cable": "https://www.thecable.ng",
    "Daily Graphic": "https://www.graphic.com.gh",
    "Citi FM/Newsroom": "https://citinewsroom.com",
    "Joy Online / JoyFM": "https://www.myjoyonline.com",
    "The Fourth Estate": "https://4thestategh.com",
    "Le Soleil": "https://www.lesoleil.sn",
    "Seneweb": "https://www.seneweb.com",
    "Abidjan.net": "https://news.abidjan.net",
    "L'Observateur Paalga": "https://lobservateur.bf",
    "Malijet": "https://malijet.com",
    "Guineenews": "https://guineenews.org",
    "Awoko": "https://awoko.org",
    "Politico SL": "https://politicosl.com",
    "FrontPageAfrica": "https://frontpageafricaonline.com",
    "KTN News": "https://www.ktnnews.com",
    "Citizen TV": "https://www.citizentv.co.ke",
    "Africa Uncensored": "https://africauncensored.online",
    "The Elephant (KE)": "https://www.theelephant.info",
    "Ethiopian Reporter": "https://www.ethiopianreporter.com",
    "Borkena": "https://borkena.com",
    "The Citizen (TZ)": "https://www.thecitizen.co.tz",
    "Mwananchi": "https://www.mwananchi.co.tz",
    "Daily Monitor": "https://www.monitor.co.ug",
    "New Vision": "https://www.newvision.co.ug",
    "The Observer (Uganda)": "https://observer.ug",
    "NBS Television": "https://www.nbswebsite.com",
    "The New Times (Rwanda)": "https://www.newtimes.co.rw",
    "IWACU": "https://www.iwacu-burundi.org",
    "Garowe Online": "https://www.garoweonline.com",
    "Eye Radio": "https://www.eyeradio.org",
    "ZimLive": "https://www.zimlive.com",
    "The Zimbabwe Independent": "https://theindependent.co.zw",
    "The Mast": "https://www.themastonline.com",
    "The Nation (Malawi)": "https://mwnation.com",
    "O País": "https://opais.co.mz",
    "Mmegi": "https://www.mmegi.bw",
    "The Namibian": "https://www.namibian.com.na",
    "Lesotho Times": "https://www.lestimes.com",
    "Jornal de Angola": "https://www.jornaldeangola.ao",
    "Maka Angola": "https://makaangola.org",
    "Radio Okapi": "https://www.radiookapi.net",
    "Actualité.cd": "https://actualite.cd",
    "Le Jour": "https://www.quotidienlejour.com",
    "L'Express (Mauritius)": "https://lexpress.mu",
    "Le Mauricien": "https://lemauricien.com",
    "L'Express de Madagascar": "https://www.lexpress.mg",
    "Mail & Guardian": "https://mg.co.za",
    "TimesLIVE": "https://www.timeslive.co.za",
    "Business Day": "https://www.businesslive.co.za",
    "The Citizen (SA)": "https://www.citizen.co.za",
    "EWN (Eyewitness News)": "https://ewn.co.za",
    "Sowetan": "https://www.sowetanlive.co.za",
    "City Press": "https://www.news24.com/citypress",
    "NewsDay (Zimbabwe)": "https://www.newsday.co.zw",
    "The Herald (Zimbabwe)": "https://www.herald.co.zw",
    "Daily Mail (Zambia)": "https://www.daily-mail.co.zm",
    "Malawi24": "https://malawi24.com",
    "@Verdade": "https://www.verdade.co.mz",
    "The Voice (Botswana)": "https://www.thevoicebw.com",
    "New Era": "https://www.newera.com.na",
    "Africa Report": "https://www.theafricareport.com",
    "Jeune Afrique": "https://www.jeuneafrique.com",
    "African Arguments": "https://africanarguments.org",
    "The Continent": "https://thecontinent.org",
    "Quartz Africa": "https://qz.com/africa",
    # Additional base URLs for sources with no URL yet
    "elPeriódico": "https://elperiodico.com.gt",
    "La Prensa (Honduras)": "https://www.laprensa.hn",
    "La Prensa (Nicaragua)": "https://laprensa.com.ni",
    "La Prensa (Panama)": "https://www.prensa.com",
    "Semanario Universidad": "https://semanariouniversidad.com",
    "La Estrella de Panamá": "https://www.laestrella.com.pa",
    "Granma": "http://www.granma.cu",
    "CubaNet": "https://www.cubanet.org",
    "Diario Libre": "https://www.diariolibre.com",
    "AyiboPost": "https://ayibopost.com",
    "Trinidad Express": "https://trinidadexpress.com",
    "Newsday (TT)": "https://newsday.co.tt",
    "Amandala": "https://amandala.com.bz",
    "Revista Oeste": "https://revistaoeste.com",
    "La Derecha Diario": "https://www.laDerechaDiario.com.ar",
    "El Destape": "https://www.eldestapeweb.com",
    "Cuestión Pública": "https://cuestionpublica.com",
    "VTV (Venezolana de Televisión)": "https://www.vtv.gob.ve",
    "Página Siete": "https://www.paginasiete.bo",
    "Erbol": "https://erbol.com.bo",
    "El Surtidor": "https://www.elsurtidor.com",
    "El Observador (Uruguay)": "https://www.elobservador.com.uy",
    "Compact": "https://www.compact-online.de",
    "Jacobin (DE)": "https://jacobin.de",
    "TheJournal FactCheck": "https://www.thejournal.ie/factcheck",
    "MTI": "https://www.mti.gov.hu",
    "Capital (BG)": "https://www.capital.bg",
    "Hlavné správy": "https://www.hlavnespravy.sk",
    "Dnevnik (Slovenia)": "https://www.dnevnik.si",
    "RTSH": "https://www.rtsh.al",
    "Efimerida ton Syntakton": "https://www.efsyn.gr",
    "APA (Azerbaijan)": "https://www.apa.az",
    "AzTV": "https://aztv.az",
    "BelTA": "https://belta.by",
    "Channel One / Perviy Kanal": "https://www.1tv.ru",
    "The Standard (HK)": "https://www.thestandard.com.hk",
    "Apple Daily Taiwan": "https://tw.appledaily.com",
    "Montsame": "https://montsame.mn",
    "UB Post": "https://theubposts.com",
    "news.mn": "https://news.mn",
    "TODAY (SG)": "https://www.todayonline.com",
    "The Jakarta Post": "https://www.thejakartapost.com",
    "Antara": "https://en.antaranews.com",
    "Project Multatuli": "https://projectmultatuli.org",
    "PCIJ": "https://pcij.org",
    "Prachatai": "https://prachatai.com",
    "VNA (Vietnam News Agency)": "https://en.vietnamplus.vn",
    "The Vietnamese": "https://www.thevietnamese.org",
    "Global New Light of Myanmar": "https://www.gnlm.com.mm",
    "VOD (Voice of Democracy)": "https://vod.com.kh",
    "Vientiane Times": "https://vientianetimes.org.la",
    "KPL (Lao News Agency)": "https://kpl.net.la",
    "Borneo Bulletin": "https://borneobulletin.com.bn",
    "Tatoli": "https://tatoli.tl",
    "Tempo Timor": "https://tempotimor.com",
    "The Economic Times": "https://economictimes.indiatimes.com",
    "Republic TV": "https://www.republicworld.com",
    "Times Now": "https://www.timesnownews.com",
    "India Today": "https://www.indiatoday.in",
    "The Quint": "https://www.thequint.com",
    "Newslaundry": "https://www.newslaundry.com",
    "OpIndia": "https://www.opindia.com",
    "Swarajya": "https://swarajyamag.com",
    "PTI (Press Trust of India)": "https://www.ptinews.com",
    "Dainik Jagran": "https://www.jagran.com",
    "Amar Ujala": "https://www.amarujala.com",
    "Dainik Bhaskar": "https://www.bhaskar.com",
    "The News Minute": "https://www.thenewsminute.com",
    "Alt News": "https://www.altnews.in",
    "Bol News": "https://www.bolnews.com",
    "APP (Associated Press of Pakistan)": "https://www.app.com.pk",
    "New Age (BD)": "https://www.newagebd.net",
    "BSS (Bangladesh Sangbad Sangstha)": "https://bss.gov.bd",
    "Sunday Times (LK)": "https://www.sundaytimes.lk",
    "Lankadeepa": "https://www.lankadeepa.lk",
    "Tamil Mirror": "https://www.tamizmirror.lk",
    "Republica": "https://myrepublica.nagariknetwork.com",
    "Online Khabar": "https://www.onlinekhabar.com",
    "Hasht-e Subh": "https://8am.af",
    "Bakhtar News Agency": "https://bakhtarnews.com.af",
    "Kuensel": "https://kuenselonline.com",
    "BBS (Bhutan Broadcasting Service)": "https://www.bbs.bt",
    "Maldives Independent": "https://maldivesindependent.com",
    "Raajje.mv": "https://raajje.mv",
    "PSM (Public Service Media)": "https://psm.mv",
    "Kazakh TV / Khabar": "https://www.khabar.kz",
    "Mediazona Central Asia": "https://centralasia.mediazona.ca",
    "UzA": "https://www.uza.uz",
    "Kloop": "https://kloop.kg",
    "Kaktus Media": "https://kaktus.media",
    "24.kg": "https://24.kg",
    "Khovar": "https://www.khovar.tj",
    "TDH (Turkmen State News)": "https://tdh.gov.tm",
    "Turkmen.news": "https://turkmen.news",
    "Chronicles of Turkmenistan": "https://www.hronikatm.com",
    "Yedioth Ahronoth / Ynet": "https://www.ynet.co.il",
    "Israel Hayom": "https://www.israelhayom.com",
    "Kan": "https://www.kan.org.il",
    "+972 Magazine": "https://www.972mag.com",
    "Channel 12 / 13 / 14": "https://www.mako.co.il",
    "Mako / N12": "https://www.mako.co.il",
    "Walla!": "https://news.walla.co.il",
    "Local Call (Sikha Mekomit)": "https://www.mekomit.co.il",
    "WAFA": "https://www.wafa.ps",
    "Mondoweiss": "https://mondoweiss.net",
    "The Daily Star (Lebanon)": "https://www.dailystar.com.lb",
    "Al Manar": "https://www.almanar.com.lb",
    "MTV Lebanon": "https://www.mtv.com.lb",
    "Megaphone": "https://www.megaphone.news",
    "Petra (JNA)": "https://petra.gov.jo",
    "7iber": "https://7iber.com",
    "NRT": "https://www.nrttv.com",
    "Iraq Oil Report": "https://www.iraqoilreport.com",
    "Kirkuk Now": "https://kirkuknow.com",
    "IRNA": "https://en.irna.ir",
    "Press TV": "https://www.presstv.ir",
    "Kayhan": "https://kayhan.ir",
    "Manoto": "https://manoto.com",
    "SPA (Saudi Press Agency)": "https://www.spa.gov.sa",
    "Okaz": "https://www.okaz.com.sa",
    "Al Riyadh": "https://www.alriyadh.com",
    "WAM (Emirates News Agency)": "https://wam.ae",
    "Al Ain News": "https://www.alainnews.ae",
    "QNA": "https://www.qna.org.qa",
    "Al-Qabas": "https://www.alqabas.com",
    "KUNA": "https://www.kuna.net.kw",
    "Gulf Daily News": "https://www.gdnonline.com",
    "BNA": "https://www.bna.bh",
    "ONA (Oman News Agency)": "https://www.onaofficial.com",
    "Saba (Yemen News Agency)": "https://www.sabanews.net",
    "SANA": "https://sana.sy",
    "SY24": "https://sy-24.com",
    "The Syria Report": "https://www.syria-report.com",
    "MENA (Middle East News Agency)": "https://www.mena.org.eg",
    "LANA": "https://lana.gov.ly",
    "TAP (Tunis Afrique Presse)": "https://www.tap.info.tn",
    "La Presse de Tunisie": "https://lapresse.tn",
    "APS (Algeria)": "https://www.aps.dz",
    "MAP": "https://www.mapnews.ma",
    "NAN (News Agency of Nigeria)": "https://www.nan.ng",
    "FIJ (Foundation for Investigative Journalism)": "https://fij.ng",
    "MyJoyOnline": "https://www.myjoyonline.com",
    "GNA (Ghana News Agency)": "https://www.ghananewsagency.org",
    "APS (Senegal)": "https://www.aps.sn",
    "Fraternité Matin": "https://www.fratmat.info",
    "Connectionivoirienne": "https://connectionivoirienne.net",
    "AIB": "https://www.aib.bf",
    "L'Essor": "https://www.essor.ml",
    "AMAP": "https://www.maliweb.net",
    "Actuniger": "https://www.actuniger.com",
    "ANP (Niger)": "https://www.anp.ne",
    "AGP": "https://guineeconakry.online",
    "Daily Observer (Liberia)": "https://www.liberianobserver.com",
    "The Standard (Gambia)": "https://thestandard.gm",
    "Togoweb": "https://www.togoweb.net",
    "La Nation (Benin)": "https://www.gouv.bj",
    "A Semana": "https://www.asemana.publ.cv",
    "AMI": "https://www.ami.mr",
    "The Star (Kenya)": "https://www.the-star.co.ke",
    "Business Daily Africa": "https://www.businessdailyafrica.com",
    "The Elephant": "https://www.theelephant.info",
    "ENA (Ethiopian News Agency)": "https://www.ena.et",
    "Fana Broadcasting": "https://www.fanabc.com",
    "TBC (Tanzania Broadcasting Corp)": "https://www.tbc.go.tz",
    "KT Press": "https://www.ktpress.rw",
    "RNA": "https://www.rnanews.com",
    "ABP (Burundi)": "https://www.abpinfos.com",
    "Dalsan Radio": "https://dalsanmedia.com",
    "SONNA": "https://sonna.so",
    "Radio Tamazuj": "https://radiotamazuj.org",
    "Hadas Eritrea": "https://www.shabait.com",
    "ERI-TV": "https://eri-tv.com",
    "Asmarino": "https://asmarino.com",
    "ADI (Agence Djiboutienne d'Information)": "https://www.adi.dj",
    "HZK Press": "https://hzk-press.com",
    "Midi Madagasikara": "https://www.midi-madagasikara.mg",
    "Seychelles Nation": "https://www.nation.sc",
    "SABC News": "https://www.sabcnews.com",
    "GroundUp": "https://groundup.org.za",
    "amaBhungane": "https://amabhungane.org",
    "Zambia Daily Nation": "https://www.zambiandailynation.com",
    "MANA": "https://www.manaonline.gov.mw",
    "CDD (Centro para Democracia e Desenvolvimento)": "https://cddmocambique.org",
    "AIM": "https://www.portaldogoverno.gov.mz",
    "BOPA": "https://bopa.gov.bw",
    "New Era (Namibia)": "https://neweralive.na",
    "Namibia Press Agency (Nampa)": "https://www.nampa.org",
    "Times of Eswatini": "https://www.times.co.sz",
    "Club-K": "https://club-k.net",
    "ACP (DRC)": "https://www.acpcongo.com",
    "ACI": "https://www.aci-media.net",
    "Les Dépêches de Brazzaville": "https://www.adiac-congo.com",
    "Cameroon Tribune": "https://www.cameroon-tribune.cm",
    "The Post (Cameroon)": "https://www.postwebcam.com",
    "L'Union (Gabon)": "https://www.union.sonapresse.com",
    "ASONGA": "https://asonga.gq",
    "ATPE": "https://www.atcpmedia.td",
    "ACAP": "https://radiotelecentrafrique.com",
    "Tela Nón": "https://telanon.net",
    "African Business": "https://african.business",
    "AAP (Australian Associated Press)": "https://www.aap.com.au",
    "TVNZ / 1News": "https://www.1news.co.nz",
    "NZPA / AAP NZ": "https://www.aap.com.au",
    "Pacific Islands News Association (PINA)": "https://pina.com.fj",
    "Asia Pacific Report": "https://asiapacificreport.nz",
    "RT (International)": "https://www.rt.com",
    "TeleSUR (International)": "https://www.telesurtv.net",
    "ABC News (Australia)": "https://www.abc.net.au/news",
    "The Australian Financial Review": "https://www.afr.com",
    "Daily Telegraph (AU)": "https://www.dailytelegraph.com.au",
    "Herald Sun": "https://www.heraldsun.com.au",
    "Sky News Australia": "https://www.skynews.com.au",
    "Crikey": "https://www.crikey.com.au",
    "The Saturday Paper": "https://www.thesaturdaypaper.com.au",
    "The Monthly": "https://www.themonthly.com.au",
    "Michael West Media": "https://michaelwest.com.au",
    "The Conversation (AU)": "https://theconversation.com/au",
    "Stuff": "https://www.stuff.co.nz",
    "Newsroom (NZ)": "https://www.newsroom.co.nz",
    "The Spinoff": "https://thespinoff.co.nz",
    "Fiji Times": "https://www.fijitimes.com.fj",
    "FBC News": "https://www.fbcnews.com.fj",
    "The National (PNG)": "https://thenational.com.pg",
    "Post-Courier": "https://www.postcourier.com.pg",
    "Samoa Observer": "https://www.samoaobserver.ws",
    "Matangi Tonga": "https://matangitonga.to",
    "Vanuatu Daily Post": "https://www.dailypost.vu",
    "Solomon Star": "https://www.solomonstarnews.com",
    "RNZ Pacific": "https://www.rnz.co.nz/international/pacific-news",
    "The Diplomat": "https://thediplomat.com",
    "Rest of World": "https://restofworld.org",
    "ICIJ": "https://www.icij.org",
    "Global Voices": "https://globalvoices.org",
    "The Conversation": "https://theconversation.com",
    "Ground News": "https://ground.news",
    "AllSides": "https://www.allsides.com",
    "Media Bias/Fact Check": "https://mediabiasfactcheck.com",
    "Bivol": "https://bivol.bg",
    "BIRN Serbia": "https://birn.eu.com",
    "CIN (Center for Investigative Reporting)": "https://cin.ba",
    "Meta.mk": "https://meta.mk",
    "MIA": "https://mia.mk",
    "Prizma": "https://prizma.mk",
}

COMMON_RSS_PATHS = [
    "/feed",
    "/feed/",
    "/rss",
    "/rss/",
    "/rss.xml",
    "/feed.xml",
    "/atom.xml",
    "/news/rss",
    "/news/feed",
    "/rss/news",
    "/api/feed",
    "/feeds/rss.xml",
    "/feeds/posts/default",
    "/?feed=rss2",
    "/feed/rss",
    "/feed/rss2",
    "/news/rss.xml",
    "/rss2.xml",
    "/sitemap_rss.xml",
]

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}

TIMEOUT = aiohttp.ClientTimeout(total=15)


async def find_rss_from_homepage(session: aiohttp.ClientSession, base_url: str) -> str | None:
    """Fetch homepage and look for RSS/Atom link tags."""
    try:
        async with session.get(base_url, headers=HEADERS, allow_redirects=True) as resp:
            if resp.status != 200:
                return None
            text = await resp.text(errors="replace")
            soup = BeautifulSoup(text, "lxml")
            for link in soup.find_all("link", type=re.compile(r"(rss|atom)", re.I)):
                href = link.get("href", "")
                if href:
                    return urljoin(base_url, href)
    except Exception:
        pass
    return None


async def try_common_paths(session: aiohttp.ClientSession, base_url: str) -> str | None:
    """Try common RSS paths on the given base URL."""
    parsed = urlparse(base_url)
    root = f"{parsed.scheme}://{parsed.netloc}"
    for path in COMMON_RSS_PATHS:
        url = root + path
        try:
            async with session.get(url, headers=HEADERS, allow_redirects=True) as resp:
                if resp.status == 200:
                    content_type = resp.headers.get("Content-Type", "")
                    text_start = (await resp.read())[:500].decode("utf-8", errors="replace")
                    if any(
                        kw in content_type.lower() or kw in text_start.lower()
                        for kw in ("rss", "atom", "xml", "<channel>", "<feed")
                    ):
                        return url
        except Exception:
            pass
    return None


async def discover_rss(session: aiohttp.ClientSession, source_name: str, base_url: str) -> str:
    """Try to find RSS feed for a source."""
    if source_name in KNOWN_RSS:
        return KNOWN_RSS[source_name]
    url = await find_rss_from_homepage(session, base_url)
    if url:
        return url
    url = await try_common_paths(session, base_url)
    if url:
        return url
    return ""


async def process_all(df: pd.DataFrame) -> list[str]:
    """Run RSS discovery for all rows, returning a list of RSS URLs."""
    results: list[str] = [""] * len(df)
    connector = aiohttp.TCPConnector(limit=20, ssl=False)
    async with aiohttp.ClientSession(connector=connector, timeout=TIMEOUT) as session:
        tasks = []
        indices = []
        for idx, row in df.iterrows():
            name = row["Source Name"]
            if name in KNOWN_RSS:
                results[idx] = KNOWN_RSS[name]
            elif name in BASE_URLS:
                tasks.append(asyncio.create_task(discover_rss(session, name, BASE_URLS[name])))
                indices.append(idx)
            # else: leave empty — no URL known

        total = len(tasks)
        print(f"Discovering RSS for {total} sources via HTTP...", flush=True)
        done = 0
        for i, coro in enumerate(tasks):
            result = await coro
            results[indices[i]] = result
            done += 1
            if done % 25 == 0 or done == total:
                print(f"  {done}/{total} done", flush=True)

    return results


def main():
    print(f"Reading {INPUT_CSV} ...", flush=True)
    df = pd.read_csv(INPUT_CSV)
    df.reset_index(drop=True, inplace=True)

    rss_urls = asyncio.run(process_all(df))
    df["RSS_URL"] = rss_urls

    found = sum(1 for u in rss_urls if u)
    total = len(rss_urls)
    print(f"\nDone: {found}/{total} sources have an RSS URL ({total - found} missing)")

    df.to_csv(OUTPUT_CSV, index=False)
    print(f"Saved → {OUTPUT_CSV}")


if __name__ == "__main__":
    main()
